tokenizer:
  model_name: t5-large
  padding_side: right
  truncation_side: right
  pad_token_as_eos_token: False
  model_max_length: 1024

reward_fn:
  id: editmatch
  args:
    metric:
      prompt_path: "./data/morality_change_this/prompt_new.txt"
      separator: "\n\n---\n\n"
      downstream_metric_name: mse
      openai_key: "..."
      gpt3_model_name: code-davinci-002
      cache_path: "./openai_summ_output/cache_me.json"
      save_path: ""
      append_feedback_to_q: True
    tokenizer:
      model_name: t5-large
      padding_side: right
      truncation_side: right
      pad_token_as_eos_token: False
  
datapool:
  id: morality
  args:
    prompt_prefix: "Generate a schema to evaluate morality:"
    stage: ppo
    folder_path: "morality_combined_gpt_caliberated"

env:
  n_envs: 2
  args:
    max_prompt_length: 30
    max_episode_length: 180
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

alg:
  id: ppo
  args: 
    n_steps: 512
    batch_size: 16
    verbose: 0
    learning_rate: 0.000001
    n_epochs: 3
    ent_coef: 0.001
  kl_div:
    coeff: 0.01
    target_kl: 2.0
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: ../trainer_schema_gen/checkpoint
      apply_model_parallel: True
      prompt_truncation_side: "right"
      optimizer_kwargs:
        weight_decay: 0.01
      generation_kwargs:
        do_sample: True
        top_k: 0
        temperature: 0.7
        min_length: 20
        max_new_tokens: 30
    
train_evaluation:
  eval_batch_size: 16
  seed: 0
  n_iters: 18
  eval_every: 1
  save_every: 1
  metrics:
    - id: editmatch
      args: 
        prompt_path: "./data/morality_change_this/prompt_new.txt"
        separator: "\n\n---\n\n"
        downstream_metric_name: mse
        openai_key: "..."
        gpt3_model_name: code-davinci-002
        cache_path: "./openai_summ_output/cache_me.json"
        save_path: ""
        append_feedback_to_q: True
        lambda_rouge_input: 4
  generation_kwargs:
    do_sample: False
    temperature: 0.0
    min_length: 20
    max_new_tokens: 150




#  96 scenarios
# 16 enviroments
#  num_steps = 120
# n_iters = 3
# no of iterations= 3 * 16 * (100 / 10) = 480
#  16 * 120 = 1920
#  1920 / 64 = 30